config/routes.rb
Kristine::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages

match '/faq', to: 'static_pages#faq', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'messages#new', via: 'get'
  match '/baked_goods', to: 'static_pages#baked_goods', via: 'get'
    match '/paper_goods', to: 'static_pages#paper_goods', via: 'get'
  match '/party_favors', to: 'static_pages#party_favors', via: 'get'
    match '/events', to: 'static_pages#events', via: 'get'

  root 'static_pages#home'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    before_save :update_priority

      validates :title, presence: true, length: { maximum: 25 }
    validates :image, presence: true
    validates :bullet_point_1, length: { maximum: 75 }
    validates :bullet_point_2, length: { maximum: 75 }
    validates :bullet_point_3, length: { maximum: 75 }
    validates :bullet_point_4, length: { maximum: 75 }

  def update_priority
    if self.priority.blank?
      lowest_priority = Carousel.order("priority DESC").first.priority
      if lowest_priority != nil
        self.priority = lowest_priority + 1
      else
        self.priority = 1
      end
    elsif Carousel.exists?(priority: self.priority)
      Carousel.where('priority >= ?', self.priority).reverse!.each do |x|
      Carousel.find(x).increment!(:priority)
      end
    else
      self.priority
    end

  end
end

app/models/message.rb
class Message
  include ActiveAttr::Model
  
  attribute :name
  attribute :email
  attribute :phone
  attribute :best_time
  attribute :content
  
  validates_presence_of :name

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX } 
  validates_length_of :content, :maximum => 500


  validates :best_time, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    before_filter :carousel_variables
    before_filter :globals

  protect_from_forgery with: :exception

    
end

def carousel_variables
        @carousel_slides = Carousel.all.order("priority")


    

end

def globals
   @message = Message.new
  end

Carousel.all(:select => "Max(priority)")

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      ContactMailer.contact_message(@message).deliver
      redirect_to :back, notice: "Message sent! Thank you for contacting us, we will respond shortly."
    else
      render "new"
    end
  end
end

 def new
    @message=Message.new
  end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @message = Message.new
  end



  def contact
  end

  def about
  end

  def baked_goods
  end

  def events
  end

  def party_favors
  end

  def paper_goods
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

 def full_title(page)
    base_title = "Sweet Little Buttercups"
    if page.empty?
      base_title
    else "#{base_title} | #{page}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_carousel.html.erb
    <ul id="roundabout-carousel">

     <% @carousel_slides.each do |slide| %>
    
    <li><%= image_tag(slide.image) %>    <h1 class="carousel-center-title"><%= slide.title %></h1>
</li>
    <% end %>

<%= link_to "#", id: "previous" do %>
 <i class="fa fa-angle-left fa-3x"></i> 
 <% end %>
<%= link_to "#", id: "next" do %>
 <i class="fa fa-angle-right fa-3x"></i> 
 <% end %>
 </ul> 


  

app/views/layouts/_footer.html.erb
<div class="col-md-12 text-right hidden-xs ">

  <nav class="navbar navbar-default text-center zero-padding  col-md-12" role="navigation">
    <ul class="nav navbar-nav zero-padding ">
      <li><%= link_to "Baked Goods", baked_goods_path %></li>
      <li><%= link_to "Paper Goods", paper_goods_path %></li>
      <li><%= link_to "Party Favors", party_favors_path %></li>
      <li><%= link_to "Events", events_path %></li>
      <li><%= link_to "About Me", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
   

  </nav>

</div>
<div class="row ">
  
  <div class= "col-md-4 text-center hidden-xs left_footer_column ">
    <h4>Visit Our Friends At:</h4>
    <address class="text-left">
      <strong>Mulberry Market</strong><br>
     30 New Jersey Rte.34<br>
     Colts Neck, NJ 07722<br>
     <abbr title="Phone">P:</abbr> (732) 683-0202
    </address>
  </div>
  
  <div class="col-md-4 text-center   ">
                  <%= link_to image_tag('logo_transparent_background3.png'), root_path %>
  </div>

  <div class="col-md-4 text-center web-designer">
    <strong> Site Designed By: <%= mail_to("sethaltshuler@gmail.com", "Seth B. Atshuler") %></strong>
  </div>
  
</div>

app/views/layouts/_header.html.erb
<!-- Desktop Navbar -->
<div class="col-md-12 text-right hidden-xs">
<div class="col-md-4 col-sm-3">
    <%= link_to image_tag('logo_transparent_background3.png', alt: "Sweet Little Buttercups", class: "logo pull-left"), root_path  %>
 </div>
    <div class="col-md-8 col-sm-9 zero-padding ">
  <nav class="navbar navbar-default text-center zero-padding  col-md-12" role="navigation">
    <ul class="nav navbar-nav pull-right zero-padding ">
      <li><%= link_to "Baked Goods", baked_goods_path %></li>
      <li><%= link_to "Paper Goods", paper_goods_path %></li>
      <li><%= link_to "Party Favors", party_favors_path %></li>
      <li><%= link_to "Events", events_path %></li>
      <li><%= link_to "About Me", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
    <div class="col-md-10 col-md-offset-2 col-sm-12 pull-right header-contact-info">
      ***Proudly Serving Central New Jersey***&nbsp;&nbsp;
      <i class="fa fa-phone "></i><span text-centers>(555)555-5555</span>&nbsp;&nbsp;
      <span class="header-icons">
        <%= link_to("#") do %><i class="fa fa-facebook-square "></i><% end %>&nbsp;
        <%= link_to("#") do %><i class="fa fa-twitter-square "></i><% end %>
      </span>
      <br />
      <%= link_to("Set Up Consultation", contact_path, class: "custom-btn btn btn-default btn-lrg")  %>
    </div>

  </nav>
</div>
</div>
<!-- /Desktop Navbar -->


<!-- Mobile  -->
  <nav class="navbar navbar-default visible-xs mobile_navbar" role="navigation">
<!-- Logo -->
    <div class="col-sm-12 text-center">
      <%= link_to image_tag('logo_transparent_background3.png', alt: "Sweet Little Buttercups", class: "logo"), root_path  %>
    </div>

<!-- Navbar -->
    <div class="navbar-header text-center">
      <a class="navbar-brand " href="#">MENU</a>
      <button type="button" class="navbar-toggle pull-none" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Baked Goods", baked_goods_path %></li>
      <li><%= link_to "Paper Goods", paper_goods_path %></li>
      <li><%= link_to "Party Favors", party_favors_path %></li>
      <li><%= link_to "Events", events_path %></li>
      <li><%= link_to "About Me", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
      </ul>
    </div>
<!-- /Navbar -->
  </nav>
<!-- /Mobile -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One|Spinnaker|Aladin' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
<script src="jquery.maskedinput.js" type="text/javascript"></script>
<%= favicon_link_tag '/favicon.ico' %>
</head>
<body>

<header>

  <%= render 'layouts/header' %>
</header>



<div class="main-body">
<% if params[:action] == "home" %>
  <%= render 'layouts/carousel' %>
<% end %>
<div class="<% if params[:action] != "home" %> page <% end %>">
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key} transparent-black-background text-center") %>
<% end %>
<div class="<%= params[:controller]%>_<%= params[:action] %>">
<%= yield %>
</div>
</div>
<footer>
  <%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/messages/new.html.erb
<%= provide(:title, 'Contact Us') %>
<ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active"><%= link_to "Contact", contact_path%></li>
</ol>
<h1 class="blank">Contact Us</h1>

<div class="contact-us-page">
  <div class="row">

<!-- Contact page text  -->
    <div class="col-md-8  contact-page-text">
      <div class="jumbo-font" class="text-center">LET'S TALK</div>
      <div class="large-font">PLANNING A PARTY?</div>
      <div class="large-font">NEED A TASTY GIFT?</div>
      <div class="large-font">LOOKING FOR THAT SPECIAL FAVOR?</div>
      <p>In order to ensure <strong>100% CUSTOMER SATISFACTION</strong> we would like to get to know you and what you are looking for.  Have an idea?  We will do everything we can to make your dream a reality.  Not sure what you are looking for?  With our years of experience we will have plenty of ideas and suggestions to get yo started in the right direction.  We use only the freshest ingredients and higest quality products.  You can give us a call at <strong>(555)555-5555</strong> or send us a message with any relevant informatin ane wee will be in touch.  We look forward to talking to you.</p>
    </div>
<!-- /Contact page text -->

<!-- Contact page form -->
    <div class="col-md-4 contact-form">
      <%= form_for @message do |f| %>
        <% if @message.errors.any? %>
          <div class="error_messages">
            <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>
            <ul>
              <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= render 'shared/fields', f: f %>
        <div class="form-group text-center">
          <%= f.submit "Talk To Us", class: "btn btn-default btn-primary" %>    
        </div>
      <% end %>
    </div>
<!-- /Contact page form -->

  </div>
</div>

app/views/shared/_fields.html.erb
<div class="form-group <% if params[:action] == "home" %>col-md-6 <% else %> col-sm-6 col-md-12 <% end %>">
  <%= f.label :name %><br />
  <%= f.text_field :name, class: "form-control " %>
</div>

<div class="form-group <% if params[:action] == "home" %>col-md-6 <% else %> col-sm-6 col-md-12  <% end %>">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  </div>

<div class="form-group <% if params[:action] == "home" %>col-md-4  <% else %> col-sm-4 col-md-12 telephone <% end %>">
  <%= f.label :phone %>
  <%= f.telephone_field :phone, class: "form-control", id: "phone" %>
</div>

<div class="form-group <% if params[:action] == 'home' %>col-md-6 <% else %> col-sm-4 col-md-12  best-time<% end %>">
  <%= f.label :best_time, "Best Time To Call After:" %>&nbsp;&nbsp;
  <%= f.select :best_time, [ 
      ["8am", 8], ["9am", 9], ["10am", 10], ["11am", 11], ["12pm", 12], ["1pm", 13], ["2pm", 14], ["3pm", 15], ["4pm", 16], ["5pm", 17], ["6pm", 18], ["7pm", 19], ["8pm", 20], ["9pm", 21], ["10pm", 22]], class: "form-control"  %>
</div>
<div class="clearfix"></div>
<div class="form-group col-md-12">
  <%= f.label :content, "Message" %>
  <%= f.text_area :content, :rows => "15",  class: "form-control" %>
</div>

app/views/static_pages/_about_me_row.html.erb
<div class="about-me-row">
  <div class="row">

    <div class="col-md-6 col-sm-6">
      <h1 class="text-center">My Story</h1>
      <%= image_tag('family.jpg', class: 'img-responsive text-center') %>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc lacinia neque ac adipiscing sagittis. Curabitur bibendum massa quis tellus fermentum ultrices. Maecenas sed libero ut elit mollis suscipit. Nunc placerat mi mauris, vel pretium nisl commodo id. Suspendisse potenti. Phasellus porta ut risus id dictum. Fusce vulputate placerat metus et dapibus. Sed hendrerit varius diam, sed tempus libero feugiat eu. Ut vel felis ac purus dapibus gravida ac nec augue. Praesent fringilla lectus non risus lobortis accumsan. Morbi scelerisque quam dolor, vel hendrerit dolor condimentum eu. Sed ligula sapien, elementum sed scelerisque ut, rhoncus et justo. In et consequat urna, sit amet consectetur augue.</p>
    </div>

    <div class="col-md-6 col-sm-6">
      <h1 class="text-center">Schedule Consultation</h1>
      <h5>To schedule an appointment or find out more information please call me at <b>(555) 555-5555</b> or tell me about yourself and I will be in touch:</h5>
      <%= form_for @message do |f| %>
        <% if @message.errors.any? %>
          <div class="error_messages">
            <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>
            <ul>
              <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= render 'shared/fields', f: f %>
        <div class="form-group text-center">
          <%= f.submit "Send Message", class: "btn btn-default btn-primary custom-btn" %>    
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/static_pages/_contact_form.html.erb
<%= form_tag(nil, role: "form") do %> <!--  form_tag(url_for_options = {}, options = {}, &block) public -->

  <div class="form-group">
    <div class="col-md-4 col-lg-2">
      <%= label_tag("inputName", "Name") %> <!--  label_tag(name = nil, content_or_options = nil, options = nil, &block) public -->  
    </div>
    <div class="col-md-8 col-lg-8">   
      <%= email_field_tag(nil, nil, class: "form-control", id: "inputEmail", placeholder: "Name") %> <!--  email_field_tag(name, value = nil, options = {}) public -->
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 col-lg-2">
      <%= label_tag("inputemail", "Email") %> <!--  label_tag(name = nil, content_or_options = nil, options = nil, &block) public -->
    </div>
    <div class="col-md-8 col-lg-8">
      <%= field_set_tag(nil,  class: "form-control", id: "inputemail", placeholder: "Email") %> <!-- password_field_tag(name = "password", value = nil, options = {}) public -->
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 col-lg-2">
      <%= label_tag("inputphone", "Phone") %> <!--  label_tag(name = nil, content_or_options = nil, options = nil, &block) public -->
    </div>
    <div class="col-md-8 col-lg-8">
      <%= field_set_tag(nil,  class: "form-control", id: "inputphone", placeholder: "Phone") %> <!-- password_field_tag(name = "password", value = nil, options = {}) public -->
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 col-lg-4">
      <%= label_tag("inputtimetocall", "Best Time To Call After:") %> <!--  label_tag(name = nil, content_or_options = nil, options = nil, &block) public -->
    </div>
    <div class="col-md-8 col-lg-8">
      <%= select_hour(nil, ampm: true) %>    </div>
    </div>
  </div>

  <div class="form-group text-center">
    <%= link_to "contact_path" "Submit", name: nil, class: "btn btn-default"%> <!--button_tag(content_or_options = nil, options = nil, &block) public -->
  </div>

<% end %>

app/views/static_pages/_features_row.html.erb
<div class="container features-row">
  <div class="row">
    
    <div class="col-md-4 col-sm-4 col-xs-12">
    <div class="features-row-header">
      <div class="row">
        <%= image_tag('nicubunu_Chocolate_birthday_cake.svg', class: 'img-responsive clip-art') %>
      </div>  
      <div class="row">
        <h1 class="text-center">BAKED GOODS</h1>
      </div>
      </div>
      <ul class="">
        <li><i class="fa fa-star fa-2x"></i><span>Cakes</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>Cookies</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>Macaroons</span></li>
      </ul>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="features-row-header">
      <div class="row">
      <%= image_tag('ryanlerch_Artwork_-_paintbrush_scissors_and_glue.svg', class: 'img-responsive clip-art') %>
    </div>  
    <div class="row">
    <h1 class="text-center">CRAFTS</h1>
</div>
</div>
 <ul class="">
        <li><i class="fa fa-star fa-2x"></i><span>Invitations</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>Party Favors</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>Gifts</span></li>
      </ul>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="features-row-header">
      <div class="row">
      <%= image_tag('party1.svg', class: 'img-responsive clip-art') %>
    </div>  
    <div class="row">
    <h1 class="text-center">PARTY PLANNING</h1>
</div>
</div>
 <ul class="">
        <li><i class="fa fa-star fa-2x"></i><span>Birthday Parties</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>School Functions</span></li>
        <li><i class="fa fa-star fa-2x"></i><span>Charity Functions</span></li>
      </ul>
    </div>


  </div>
</div>

app/views/static_pages/_scrolling_quotes.html.erb
<div class="row scrolling_quote">
  <div class="col-md-12">
    <div class="titlebox">       Testimonials      </div>
    <div class="quotes">"enean molestie vestibulum neque, sed auctor enim. Suspendisse convallis ante id tempor placerat. Nulla molestie aliquet fermentum. Curabitur quis fringilla sem, ac dapibus elit. Vestibulum iaculis, leo non mollis eleifend, risus ligula ornare neque, ut suscipit mi nibh vitae quam. Nulla nulla diam, lacinia nec tellus sit amet, blandit malesuada dui. Donec volutpat rutrum sem, interdum commodo justo scelerisque a.."
      <br />
      <div class="source">
        -Example 1
      </div>
    </div>
    <div class="quotes">"et fermentum. Curabitur quis fringilla sem, ac dapibus elit. Vestibulum iaculis, leo non mollis eleifend, risus ligula ornare neque, ut suscipit mi nibh vitae quam. Nulla nulla diam, lacinia nec tellus sit amet, blandit malesuada dui. Donec volutpat rutrum sem, interdum commodo justo scelerisque a.."<br />
      <div class="source">
        -Example 2
              </div>
    </div>
    <div class="quotes">"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean molestie vestibulum neque, sed auctor enim. Suspendisse convallis ante id tempor placerat. Nulla molestie aliquet fermentum. Curabitur quis fringilla sem, ac dapibus elit.. Nulla nulla diam, lacinia nec tellus sit amet, blandit malesuada dui. Donec volutpat rutrum sem, interdum commodo justo scelerisque a."<br />
      <div class="source">
        -Example 3.
      </div>
    </div>
   
  </div>
</div>

app/views/static_pages/about.html.erb
<%= provide(:title, "About Us") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/baked_goods.html.erb
<!-- sheet cakes, layered cakes, cookies, macaroons, truffles -->
<%= provide(:title, "Baked Goods") %>
<ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li class="active"><%= link_to "Baked Goods", baked_goods_path %></li>
</ol>
<h1 class="text-center">Baked Goods</h1>


<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
            <%= image_tag("cake_1.png") %>             
            <div class="caption">
                <h2>Layered Cakes</h2>
            </div>
        </div>
    </div>
<% end %>

<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
<%= image_tag("dessert_4.jpg") %>             <div class="caption">
                <h2>Sheet Cakes</h2>
                
            </div>
        </div>
    </div>
<% end %>

<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
<%= image_tag("dessert_3.jpg") %>             <div class="caption">
                <h2>Cookies</h2>
                
            </div>
        </div>
    </div>
<% end %>

<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
<%= image_tag("Valentines_Heart.png") %>             <div class="caption">
                <h2>Macaroons</h2>
                
            </div>
        </div>
    </div>
<% end %>

<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
<%= image_tag("favor_1.png") %>             <div class="caption">
                <h2>Cupcakes</h2>
                
            </div>
        </div>
    </div>
<% end %>

<%= link_to "#" do %>
    <div class = "col-md-6 col-lg-4 col-sm-12">
        <div class="thumbnail">
<%= image_tag("cake_2.png") %>             <div class="caption">
                <h2>Truffles</h2>
                
            </div>
        </div>
    </div>
<% end %>    

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact Us") %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/events.html.erb
<%= provide(:title, "Events") %>
<h1 class = "text-center coming-soon">Coming Soon...</h1>

app/views/static_pages/faq.html.erb
<%= provide(:title, 'FAQ') %>
<h1>StaticPages#faq</h1>
<p>Find me in app/views/static_pages/faq.html.erb</p>

app/views/static_pages/home.html.erb
<section>
<%= render 'features_row' %>
</section>
<section>
<%= render 'scrolling_quotes' %>
</section>
<section>
<%= render 'about_me_row' %>
</section>

app/views/static_pages/paper_goods.html.erb
<%= provide(:title, "Paper Goods") %>
<h1 class = "text-center coming-soon">Coming Soon...</h1>

app/views/static_pages/party_favors.html.erb
<%= provide(:title, "Party Favors") %>
<h1 class = "text-center coming-soon">Coming Soon...</h1>